output() {
# set the ERR trap so that the output function exits on error
trap on_error ERR
